[build]
  publish = "sites/citizenlab/dist"
  command = "git submodule update --remote && pnpm i && cd sites/citizenlab && pnpm run build"
[build.processing.html]
  pretty_urls = false
[[headers]]
  for = "/_astro/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
